#exec-on-workspace-change = ['/bin/bash', '-c',
#    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
#]

#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[workspace-to-monitor-force-assignment]
 1 = 1
 2 = 2
 3 = 3
 4 = 1
 5 = 2
 6 = 3
 7 = 1
 8 = 2
 9 = 3
10 = 1

[gaps]
inner.horizontal = 5
inner.vertical   = 5
outer.left       = 0
outer.bottom     = 0
# todo fix this
# outer.top        = [{ monitor.'built-in' = 15 }, { monitor.main = 39 }, 15]
outer.top        = 1
outer.right      = 0

[mode.main.binding]
alt-enter = 'exec-and-forget /Applications/Alacritty.app/Contents/MacOS/alacritty'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

ctrl-shift-h = 'focus-monitor left'
ctrl-shift-j = 'focus-monitor down'
ctrl-shift-k = 'focus-monitor up'
ctrl-shift-l = 'focus-monitor right'

alt-shift-a='focus-monitor 1'
alt-shift-b='focus-monitor 2'
alt-shift-c='focus-monitor 3'

alt-f = 'fullscreen'
alt-s = 'layout h_accordion'
alt-v =  'layout v_accordion'
alt-shift-s='layout h_tiles'
alt-shift-v='layout v_tiles'

cmd-shift-space = 'layout floating tiling'

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-0 = 'workspace 10'

ctrl-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
ctrl-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
ctrl-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
ctrl-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
ctrl-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
ctrl-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
ctrl-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
ctrl-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
ctrl-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
ctrl-shift-0 = ['move-node-to-workspace 10', 'workspace 10']

cmd-shift-c = 'reload-config'
# cmd-shift-n = ['move-node-to-monitor next', 'focus-monitor next']
# cmd-shift-p = ['move-node-to-monitor prev', 'focus-monitor prev']

cmd-shift-h = ['move-node-to-monitor left', 'focus-monitor left']
cmd-shift-j = ['move-node-to-monitor down', 'focus-monitor down']
cmd-shift-k = ['move-node-to-monitor up', 'focus-monitor up']
cmd-shift-l = ['move-node-to-monitor right', 'focus-monitor right']

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

#[[on-window-detected]]
#if.app-id = 'org.alacritty'
#run = 'move-node-to-workspace 2'
#
#[[on-window-detected]]
#if.app-id = 'net.whatsapp.WhatsApp'
#run = 'move-node-to-workspace 6'
#
#[[on-window-detected]]
#if.app-id = 'com.tinyspeck.slackmacgap'
#run = 'move-node-to-workspace 7'
#
#[[on-window-detected]]
#if.app-id = 'com.hnc.Discord'
#run = 'move-node-to-workspace 8'
#
#[[on-window-detected]]
#if.app-id = 'com.spotify.client'
#run = 'move-node-to-workspace 9'
