#! /usr/bin/env python3
import sys

def processOutput():
    if len(sys.argv) > 1:
        return sys.argv[1]
    else:
        return sys.stdin.read()

# note doesn't work with mutliple @ or :'s 
# todo sanitize
def convertToHttp(str):

  str = str.split('@')[1]
  str = str.replace(':','/')
  return 'https://'+str

print(convertToHttp(processOutput()))
